doctrine:
  dbal:
    driver: pdo_mysql
    host: 172.23.0.2
    port: 3306
    dbname: app
    user: root
    password: root

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
